service: digihome-frontend
image: heimby/digihome-frontend

servers:
  web:
    - 65.21.252.58

proxy:
  ssl: true
  hosts:
    - digihome.no
    - www.digihome.no

registry:
  server: ghcr.io
  username: mathiash98

  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  # Use local context instead of only committed files
  context: .
  arch: [arm64]
  # Using remote builder as the github action runner is not on amd64
  remote: ssh://root@65.21.252.58
  args:
    APP_BUILD: next
    APP_BUILD_DATE: <%= Time.now.strftime("%Y-%m-%dT%H:%M:%S%z") %>
    APP_VERSION: 0.1.0
